# Generated by Django 6.0 on 2025-12-09 16:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидание игроков'), ('active', 'Игра идёт'), ('finished', 'Завершена')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('level_duration_seconds', models.IntegerField(default=300)),
                ('min_players', models.IntegerField(default=2)),
                ('auto_start', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('device_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ready', 'Готов'), ('playing', 'В игре'), ('done', 'Завершил')], default='ready', max_length=20)),
                ('current_level', models.CharField(choices=[('none', 'Не начал'), ('green', 'Зелёный'), ('yellow', 'Жёлтый'), ('red', 'Красный')], default='none', max_length=20)),
                ('total_score', models.IntegerField(default=0)),
                ('bonus_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.session')),
            ],
            options={
                'ordering': ['-total_score', '-bonus_score', 'created_at'],
                'unique_together': {('session', 'device_uuid')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='game.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('green', 'Зелёный'), ('yellow', 'Жёлтый'), ('red', 'Красный')], max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершён'), ('failed', 'Провален')], default='in_progress', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('time_spent_ms', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='game.player')),
            ],
            options={
                'ordering': ['level', 'created_at'],
                'unique_together': {('player', 'level')},
            },
        ),
    ]
