# Generated by Django 6.0 on 2025-12-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='device_uuid',
            field=models.UUIDField(db_index=True),
        ),
    ]
