# Generated by Django 6.0 on 2025-12-09 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_player_device_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selfie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='selfies/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfies', to='game.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfies', to='game.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
