# Generated by Django 6.0 on 2025-12-09 21:03

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_selfie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfie',
            name='image',
            field=models.ImageField(upload_to=game.models.selfie_upload_path),
        ),
    ]
