# Generated by Django 6.0 on 2025-12-10 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_selfie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='role_buff',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CrashGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('multiplier', models.FloatField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crash_games', to='game.session')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CrashBet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('multiplier', models.FloatField()),
                ('bet_amount', models.IntegerField(default=0)),
                ('win_amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('won', 'Выиграл'), ('lost', 'Проиграл')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crash_bets', to='game.player')),
                ('crash_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='game.crashgame')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('crash_game', 'player')},
            },
        ),
    ]
