# Generated by Django 6.0 on 2025-12-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_role_player_role_buff_crashgame_crashbet'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashbet',
            name='cashed_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crashbet',
            name='cashout_multiplier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crashgame',
            name='betting_phase_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crashgame',
            name='betting_phase_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crashgame',
            name='duration_seconds',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='crashgame',
            name='nonce',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crashgame',
            name='seed',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='crashgame',
            name='server_seed',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='crashgame',
            name='server_seed_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='crashbet',
            name='multiplier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crashbet',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('cashed_out', 'Выведено'), ('won', 'Выиграл'), ('lost', 'Проиграл')], default='pending', max_length=20),
        ),
    ]
