# Generated by Django 6.0 on 2025-12-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_admin_and_player_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_green_game',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='current_red_game',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='current_yellow_game',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='played_bonus_games',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
